name: 'Auto Release Draft'
description: 'Draft a GiotHub Release'
author: 'Ramya Ramadasan'
#inputs:
#  milliseconds: # change this
#    required: true
#    description: 'input description here'
#    default: 'default value if applicable'
outputs:
  release-url:
  description: "URL of the GitHub Release that was drafted"
runs:
  using: 'node12'
  main: 'dist/index.js'
